#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

// Gameplay Ability Tags.
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GAMEPLAYABILITY_DODGE)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GAMEPLAYABILITY_COOLDOWN)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GAMEPLAYABILITY_COOLDOWN_DODGE)

// Gameplay Effect Tags.
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GAMEPLAYEFFECT_STATUS_STAMINA_REGEN)

// Gameplay Cue Tags.
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GAMEPLAYCUE_DODGE_START)

// Data Tags.
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_DATA_DAMAGE)

// Event Tags.
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_EVENT_EQUIPITEM)

// Message Channels.
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MESSAGE_ATTRIBUTECHANGE_HEALTH)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MESSAGE_ATTRIBUTECHANGE_STAMINA)

// Inventory System.
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_EQUIPMENT_SLOT_LEFT)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_EQUIPMENT_SLOT_RIGHT)

